controllers/MonitoringController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\helpers\Wialon;
use app\models\Machine;
use app\models\Category;
use app\helpers\FormatterHelper;

class MonitoringController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {        
        $model = Machine::getCurrent();
        return $this->render('index', [
            'model' => $model
        ]);
    }
    
    public function actionTest()
    {        
        return $this->render('test');
    }
    
    public function actionInfo()
    {        
        $model = Machine::getCurrent();
        $categories = Category::find()->where(['machine_id' => $model->id, 'parent_id' => null]) ->all();
        
        return $this->render('info', [
            'model' => $model,
            'categories' => $categories,
        ]);
    }
    
    public function actionCondition()
    {        
        $model = Machine::getCurrent();
        
        return $this->render('condition', [
            'model' => $model
        ]);
    }
    
    public function actionRoute()
    {        
        $model = Machine::getCurrent();
        $post = Yii::$app->request->post();
        $interval = null;
        if ($post) {
            $interval = $post;
            if ($post['typeInterval'] == 'timeAgo') {
                $time = (isset($post['currentInterval'])) ? strtotime($post['choose-interval-from']) : time();
                $interval['from'] = $time - $post['periodLength'] * $post['periodType'];
                $interval['to'] = $time;
            } else {
                $interval['from'] = strtotime($post['choose-interval-from']);
                $interval['to'] = isset($post['choose-interval-to']) ? strtotime($post['choose-interval-to']) : time();
            }
            if ($interval['from'] > $interval['to']) {
                $_from = $interval['from'];
                $interval['from'] = $interval['to'];
                $interval['to'] = $_from;
            }
        }
        
        return $this->render('route', [
            'model' => $model,
            'interval' => $interval,
        ]);
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use app\assets\AppAsset;
use app\components\widgets\ChooseMachineWidget;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap navbar">
    <header>
        <h1><?= Html::encode($this->title) ?></h1>        
        <?= Html::a(
            Html::tag(
                'div', 
                Html::tag('span', 'Акционерное Общество', ['class' => 'org-form']) .
                Html::tag('span', 'КурганАвтоРемонт', ['class' => 'org-name']),
                ['class' => 'title']
            ).
            Html::img(['images/logo.png']),
            ['/site/index'],
            ['class' => 'logo']
        );?>
        <?= ChooseMachineWidget::widget() ?>
    </header>
    <?php
    NavBar::begin([
        'options' => [
            'class' => 'navbar-custom',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-left'],
        'items' => [
            ['label' => 'Главная', 'url' => ['/monitoring/index']],
            ['label' => 'Информация', 'url' => ['/monitoring/info']],
            ['label' => 'Состояние', 'url' => ['/monitoring/condition']],
            ['label' => 'Маршрут', 'url' => ['/monitoring/route']],
            ['label' => 'Бурение', 'url' => ['#']],
            ['label' => 'Статистика', 'url' => ['#']],
            ['label' => 'Ресурс', 'url' => ['#']],
            ['label' => 'Обслуживание', 'url' => ['#']],
            ['label' => 'Корректировка', 'url' => [(Yii::$app->user->can('admin')) ? '/admin' : '#' ]],
            Yii::$app->user->isGuest ? (
                ['label' => 'Авторизация', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Выход (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>